'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class APP_Dati

    'Simple Properties
    <DataMember()>
    Public Property ID As String
    <DataMember()>
    Public Property Tipo As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Codice As String
    <DataMember()>
    Public Property Dati As String
    <DataMember()>
    Public Property Riferimento As String
    <DataMember()>
    Public Property cancellato As Nullable(Of Short)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Importato_Data As Nullable(Of Date)
    <DataMember()>
    Public Property Importato_Errore As String
    <DataMember()>
    Public Property Data_Invio_Sistema_Logging As Nullable(Of Date)
    <DataMember()>
    Public Property User_Agent As String

End Class
