'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class C_SpecieVarieta

    'Simple Properties
    <DataMember()>
    Public Property cod_specie_cliente As Double
    <DataMember()>
    Public Property cod_varieta_cliente As Double
    <DataMember()>
    Public Property veg_cod As Double
    <DataMember()>
    Public Property desc_specie_cliente As String
    <DataMember()>
    Public Property cul_cod As Double
    <DataMember()>
    Public Property desc_varieta_cliente As String
    <DataMember()>
    Public Property grva_cod_veg As Double
    <DataMember()>
    Public Property grva_cod As Nullable(Of Double)

End Class
