'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class cbl_transcodificaSpecieXCultivar

    'Simple Properties
    <DataMember()>
    Public Property varietaCal As String
    <DataMember()>
    Public Property Veg_Cod As Integer
    <DataMember()>
    Public Property Cul_Cod As Integer

End Class
