'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class cbl_transcodificaCalibri

    'Simple Properties
    <DataMember()>
    Public Property DescrizioneCbl As String
    <DataMember()>
    Public Property DescrizioneGias As String
    <DataMember()>
    Public Property Tabella_Par_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Veg_Cod As String

End Class
