'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(MenuBS_2017_Sezioni))>
<KnownType(GetType(MenuBS_2017_TipoSezioni))>
Partial Public Class MenuBS_2017_Sezioni

    'Simple Properties
    <DataMember()>
    Public Property IDSezione As Integer
    <DataMember()>
    Public Property Testo As String
    <DataMember()>
    Public Property id_html As String
    <DataMember()>
    Public Property ClasseCSS As String
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property Pubblica As Nullable(Of Integer)
    <DataMember()>
    Public Property IDLingua As Nullable(Of Integer)
    <DataMember()>
    Public Property PivaSuperUser As String
    <DataMember()>
    Public Property Piva As String
    <DataMember()>
    Public Property Colonna_Bootstrap As String
    <DataMember()>
    Public Property Colore As String
    <DataMember()>
    Public Property IDSezionePadre As Nullable(Of Integer)
    <DataMember()>
    Public Property ID_Attivita As Nullable(Of Integer)
    <DataMember()>
    Public Property IDTipoSezione As Nullable(Of Integer)
    <DataMember()>
    Public Property Ordinamento As Nullable(Of Integer)
    <DataMember()>
    Public Property RichiedeAziendaSelezionata As Nullable(Of Integer)
    <DataMember()>
    Public Property Enum_SiteRedirector As Nullable(Of Integer)
    <DataMember()>
    Public Property PaginaRichiesta As Nullable(Of Integer)
    <DataMember()>
    Public Property RedirectURL As String
    <DataMember()>
    Public Property Enum_TipoAperturaPagina As Nullable(Of Integer)

    'Navigation Properties
    <DataMember()>
    Public Overridable Property MenuBS_2017_Sezioni1 As ICollection(Of MenuBS_2017_Sezioni) = New HashSet(Of MenuBS_2017_Sezioni)
    <DataMember()>
    Public Overridable Property MenuBS_2017_Sezioni2 As MenuBS_2017_Sezioni
    <DataMember()>
    Public Overridable Property MenuBS_2017_TipoSezioni As MenuBS_2017_TipoSezioni

End Class
