'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Ricette_Operazioni

    'Simple Properties
    <DataMember()>
    Public Property Ricetta_SuperUser As String
    <DataMember()>
    Public Property Ricetta_Cod As Integer
    <DataMember()>
    Public Property Ricetta_Operazione_Cod As Integer
    <DataMember()>
    Public Property Ricetta_Operazione_Des As String
    <DataMember()>
    Public Property Lav_Cod As Integer
    <DataMember()>
    Public Property Note As String
    <DataMember()>
    Public Property Num_Protocollo As Nullable(Of Double)
    <DataMember()>
    Public Property Id_Rcdpi As Nullable(Of Integer)
    <DataMember()>
    Public Property Extra_Int As Nullable(Of Integer)
    <DataMember()>
    Public Property Mezzo As Nullable(Of Short)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property datainvio As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)
    <DataMember()>
    Public Property DataLock As Nullable(Of Integer)
    <DataMember()>
    Public Property Gru_Op As Nullable(Of Integer)
    <DataMember()>
    Public Property Costo As Nullable(Of Double)
    <DataMember()>
    Public Property Noleggio_Passivo As Nullable(Of Short)
    <DataMember()>
    Public Property Id_Tp_Fer As Nullable(Of Integer)
    <DataMember()>
    Public Property EM_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Eff_Perc As Nullable(Of Double)
    <DataMember()>
    Public Property Disciplinare_PubblicoPrivato As Nullable(Of Integer)
    <DataMember()>
    Public Property W_Anagrafica_Stati_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Ricetta_Operazione_Cod_RIF As Nullable(Of Integer)
    <DataMember()>
    Public Property APP_Ricetta_Operazione_ID As String
    <DataMember()>
    Public Property Raccoglitore_Cod As Nullable(Of Integer)
    <DataMember()>
    Public Property Invia_App As Nullable(Of Integer)
    <DataMember()>
    Public Property Invia_HubIoT As Nullable(Of Short)

End Class
