'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
Partial Public Class Tipo_Entita_Chiavi

    'Simple Properties
    <DataMember()>
    Public Property TipoEntita_Cod As Integer
    <DataMember()>
    Public Property Nome_Chiave As String
    <DataMember()>
    Public Property Ordine As Nullable(Of Integer)
    <DataMember()>
    Public Property Obbligatorio As Nullable(Of Integer)

End Class
