'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(ws_RegVino_Operazioni_Prodotti))>
<KnownType(GetType(ws_RegVino_Vasi))>
Partial Public Class ws_RegVino_Operazioni_Prodotti_Vasi

    'Simple Properties
    <DataMember()>
    Public Property ws_RegVino_Operazione_cod As Integer
    <DataMember()>
    Public Property Prodotto_Progressivo As Integer
    <DataMember()>
    Public Property CodVaso As String
    <DataMember()>
    Public Property Vaso_Progressivo As Integer
    <DataMember()>
    Public Property CodiceIcqrf As String

    'Navigation Properties
    <DataMember()>
    Public Overridable Property ws_RegVino_Operazioni_Prodotti As ws_RegVino_Operazioni_Prodotti
    <DataMember()>
    Public Overridable Property ws_RegVino_Vasi As ws_RegVino_Vasi

End Class
