'------------------------------------------------------------------------------
' <auto-generated>
'     Codice generato da un modello.
'
'     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
'     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Runtime.Serialization    'MANUAL ADD

<Serializable()>
<DataContract(IsReference:=True)>
<KnownType(GetType(ws_SQNPI_LogInvio_Dettaglio_Errori))>
<KnownType(GetType(ws_SQNPI_Domanda))>
Partial Public Class ws_SQNPI_LogInvio

    'Simple Properties
    <DataMember()>
    Public Property ws_SQNPI_LogInvio_Cod As Integer
    <DataMember()>
    Public Property ws_SQNPI_LogInvio_Des As String
    <DataMember()>
    Public Property DataInvio As Nullable(Of Integer)
    <DataMember()>
    Public Property DataElaborazione As String
    <DataMember()>
    Public Property EsitoRicezione As Nullable(Of Integer)
    <DataMember()>
    Public Property skXml As Nullable(Of Integer)
    <DataMember()>
    Public Property Stato_Gias As Nullable(Of Integer)
    <DataMember()>
    Public Property inviato As Nullable(Of Short)
    <DataMember()>
    Public Property Data_Creazione As Nullable(Of Date)
    <DataMember()>
    Public Property Data_Modifica As Nullable(Of Date)
    <DataMember()>
    Public Property Username_Creazione As String
    <DataMember()>
    Public Property Username_Modifica As String
    <DataMember()>
    Public Property Validita_Inizio As Nullable(Of Date)
    <DataMember()>
    Public Property Validita_Fine As Nullable(Of Date)

    'Navigation Properties
    <DataMember()>
    Public Overridable Property ws_SQNPI_LogInvio_Dettaglio_Errori As ICollection(Of ws_SQNPI_LogInvio_Dettaglio_Errori) = New HashSet(Of ws_SQNPI_LogInvio_Dettaglio_Errori)
    <DataMember()>
    Public Overridable Property ws_SQNPI_Domanda As ICollection(Of ws_SQNPI_Domanda) = New HashSet(Of ws_SQNPI_Domanda)

End Class
