@loginCookie=eyJraWQiOiIyMDI1MDMyODAxMzczOXBkOXBkam04eDFsOSIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJNQVNURVIvRlJNVFRSNzZNMDZCNzE1RSIsImF1ZCI6InNzbzItbG9naW4iLCJpc3MiOiJBYmFjby1TU08yIiwiZXhwIjoxNzQzNDE4ODM3LCJfdXMiOiJtOHd4M2lrMC4xM3dydDBwIiwiaWF0IjoxNzQzNDE2Mzc3LCJ0ZW5hbnQiOiJtYXN0ZXIiLCJ1c2VybmFtZSI6IkZSTVRUUjc2TTA2QjcxNUUifQ.oLGHLZ9BO0PBxH0i5VWQkmkA5IxiD-ikkoH_2CF9WvejJ2Szr-ZdYogoUcWcQ58ZOO3vOdFiQ6-7spePluYFPppsMekvfIPIpaacksPI39YXnyEphaBIvd-9dQVrWqWalDG8r0TssMt-vi_s4HDPri6O5EbdZVZDuFwOCYl7HpAmVLIbIMENFo7hpKC8ObW5x9AvWVoek2end9jl_UJ1mz4KLZsSSTQ7kP9bWhVUCfdrS8waMoUojFMrg6SWYfcHgQqZ2LRwp6SR7__IpPLla10chnuhn06lXgv1PD9kCRqySCJA1OCJK-j82o9t4ggXZw0Awky5C6jrSXE8ns_BDA
@base=https://umbria-dev.fe.abacogroup.eu

###
# WARNING: Caricare prima i dati dei CAA in parties ACL
POST {{base}}/parties-acl-server/master/api-priv/v1/parties-acl/entities
Content-Type: application/json
Cookie: LOGIN_COOKIE={{loginCookie}}
# Authorization: APIKEY {{apikey}}

{
  "code": "REGIONE",
  "parent_code": null,
  "name": "Regione Umbria",
  "description": "Regione Umbria",
  "entity_type_code": "REGIONAL_OFFICE",
  "registry_party_id": null,
  "day_from": "20250331",
  "day_to": "99991231"
}