@loginCookie=eyJraWQiOiIyMDI0MTEwNjEwMjkzMGxrcHVuYTdxM21rNyIsInR5cCI6IkpXVCIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJNQVNURVIvQURNSU4iLCJhdWQiOiJzc28yLWxvZ2luIiwiaXNzIjoiQWJhY28tU1NPMiIsImV4cCI6MTczMDkxMTQzOSwiX3VzIjoibTM2MmlrOTMuMmxsbTY0IiwiaWF0IjoxNzMwOTA4OTc5LCJ0ZW5hbnQiOiJtYXN0ZXIiLCJ1c2VybmFtZSI6IkFETUlOIn0.ZN6s7dsXL5rk09HsyCUGqRtKEo43HmWMfeQbGThf7EbT-LyHtTIripMtSDV9SHnl60amTIzByy7vWEn19_FcoLpTNEjj7jZ5OBNnutuwXnpqWKZPSLDiLjWyofJDpuBzKrzhDTvoD4Zgo-EntQsq6YU5dO1RghDIJuBx1G5DiPkgBLBWa8qzJh6EQr8i78SaNF9abZ40zcAX37Kf4kgz5EW6YgBoz9piro6Y3Eopys9W2iHFXJUdK739MaRhBiwf8hMxM0PigBXJ_pKigsviQkOrdq4DA7876fLZI5mHlqPOSRGLn6l9LTS-rb9Z9o4g8GNwm_8lAzhi30lwwf406Q
@base=https://umbria-dev.fe.abacogroup.eu

###
# WARNING: Caricare prima i dati dei CAA in parties ACL
POST {{base}}/parties-acl-server/master/api-priv/v1/parties-acl/parties/*/users
Content-Type: application/json
Cookie: LOGIN_COOKIE={{loginCookie}}

{
    "username": "IMPORT_SERVICE_ACCOUNT",
    "role": "ADMIN",
    "description": "Import service account"
}