let regioni = [
    { text: "Non stampare logo", value: "-1" },
    { text: "Abruzzo", value: "013" },
    { text: "Basilicata", value: "017" },
    { text: "Calabria", value: "018" },
    { text: "Campania", value: "015" },
    { text: "Emilia Romagna", value: "008" },
    { text: "Friuli Venezia Giulia", value: "006" },
    { text: "Lazio", value: "012" },
    { text: "Liguria", value: "007" },
    { text: "Lombardia", value: "003" },
    { text: "Marche", value: "011" },
    { text: "Molise", value: "014" },
    { text: "Non Definita", value: "000" },
    { text: "Piemonte", value: "001" },
    { text: "Puglia", value: "016" },
    { text: "Sardegna", value: "020" },
    { text: "Sicilia", value: "019" },
    { text: "Toscana", value: "009" },
    { text: "Trentino Alto Adige", value: "004" },
    { text: "Umbria", value: "010" },
    { text: "Valle d'Aosta", value: "002" },
    { text: "Veneto", value: "005" }];

let schedaVeneto = [
    { text: "Selezione..", value: "" },
    { text: "Scheda A", value: "a" },
    { text: "Scheda B", value: "b" },
    { text: "Scheda C", value: "c" },
    { text: "Scheda D", value: "d" },
    { text: "Scheda E", value: "e" }];

let arrotondamenti = [
    { text: "Nessuno", value: "-1" },
    { text: "Unita", value: "0" },
    { text: "1 Decimale", value: "1" },
    { text: "2 Decimali", value: "2" },
    { text: "3 Decimali", value: "3" },
    { text: "4 Decimali", value: "4" }];
let magazzini = []

var ElencoReportChiave  = {
    FRONTESPIZIO: 'a',
    FERTILIZZAZIONI: 'b',
    TRATTAMENTI: "c",
    FASI_FENOLOGICHE: "d",
    TRAPPOLE_INSTALLATE: "e",
    RIL_AVVERS_NELLE_TRAPP: "f",
    RIL_AVVERS_IN_CAMPO: "g",
    IRRIGAZIONE: "h",
    ALTRE_OPER_COLTURALI: "i",
    INDICE_MAT_E_RACCOLTA: "l",
    PIOGGE: "m",
    RIL_PROD_E_DATA_RACC: "n",
    DATI_CATASTALI: "o",
    SEMINE: "p",
    INFORMAZ_E_DICHIAR: "q",
    VISITE_ISPETTIVE: "r",
    PERSONALE_CON_PATENTINO: "s",
    FITOFARMACI: "t",
    PRATICHE_ECOLOGICHE: "u",
    VERIFICHE_CONFORMITA: "v",
    FORMAZIONE: "w",
    GESTIONE_RIFIUTI: "x",
    MANUTEN_MACCHINARI: "y",
    MACCH_SOLO_DIFESA: "z",
    TRATTAMENTI_POSTRACCOLTA: "1"
};
const enum_CodificaStampe = {
    Nessuna: 0,
    SchedaCampagna_2078: 1,
    RegistroTrattamenti: 2,
    SchedaRegistrazione: 3,
    SchedaCampagna_Biologico: 4,
    Bolle: 5,
    Fatture: 6,
    Quadro_P: 7,
    PianoRaccolta: 8,
    SchedaMagazzinoMovimenti: 9,
    SchedaMagazzinoGiacenze: 10,
    SchedaMagazzinoFertilizzanti: 11,
    SchedaMagazzinoProdottiFitosanitari: 12,
    SchedaCampagna_2078_Semplificata: 13,
    RegistroTrattamenti_Semplificata: 14,
    SchedaRegistrazione_Semplificata: 15,
    SchedaCampagna_Biologico_Semplificata: 16,
    ReportRisultatoFilrone: 17,
    RiepilogoImpiegoSuperfici: 18,
    Eurep_Gap: 19,
    SchedaColturale_Biologico: 20,
    SchedaMateriePrime_Biologico: 21,
    SchedaVendite_Biologico: 22,
    Esporta_GiasToSap: 23,
    PAP_Vegetale: 24,
    SchedaTracciabilita: 25,
    ReportConserveItalia: 26,
    SchedaCampagna_ConserveItalia: 27,
    RapportinoStrube: 28,
    Eurep_Gap_Semplificata: 29,
    DatiAnelloFilieraIngresso: 30,
    DatiAnelloFilieraLegameLotti: 31,
    GestioneAllegati: 32,
    AnalisiCosti_XLS: 33,
    AnalisiRicavi_XLS: 34,
    MarginiEconomici_XLS: 36,
    SchedaTracciabilita_ByLotto: 35,
    EstrattoreDatiGrafici: 37,
    LibroConferimenti: 38,
    PianoColturale: 39,
    SchedaCampagna_Pizzoli: 40,
    Esportazione_OP_Inv: 41,
    Esportazione_OP_Gest: 52,
    Esportatore_Universale_Impianti: 42,
    Esportatore_Universale_Imprese: 43,
    Esportatore_Universale_Centri: 44,
    Esportatore_Universale_Appezza: 45,
    Esportatore_Universale_Agenda: 46,
    Esportatore_Universale_Rintraccio: 49,
    AnalisiTerreno: 47,
    Report_RiconversioneVarietale: 48,
    Report_ImpegnoProduzioneSoci: 51,
    Verifica_Conformita: 50,
    ImportaAnagrafiche_XLS2GIAS: 53,
    GestioneRicette_Lista: 54,
    Registro_FattureAcquisto: 55,
    Registro_FattureVendita: 56,
    Registro_Corrispettivi: 57,
    Registro_AltriCosti: 58,
    Registro_AltriRicavi: 59,
    Registro_PrimaNota: 60,
    Lista_InsolutiClienti: 61,
    Lista_InsolutiFornitori: 62,
    LiquidazionePeriodica_IVA: 63,
    Bilancio_Civilistico: 64,
    PianoDeiConti: 65,
    Bolle_Conferimento_Soci: 67,
    Bolle_Conferimento_Diversi: 68,
    Report_NPK_Totali: 66,
    PAP_Zootecnico: 69,
    Costo_Manodopera_XLS: 70,
    Costo_ParcoMacchine_XLS: 71,
    Analisi_Vino: 72,
    RicevuteFiscali: 73,
    Atto_Notorio: 74,
    Adesione_Etico_Ambientale: 75,
    Tenuta_Scheda_Campagna: 76,
    Adesione_DPI: 77,
    Impegnativa_Eurep: 78,
    Impegnativa_QC: 79,
    Impegnativa_Confusione_Sessuale: 80,
    Codice_Condotta: 81,
    Modello4: 82,
    Registro_Stalla: 83,
    ImportaAnagraficheAnimali_XLS2GIAS: 84,
    VasiVinari: 85,
    GestioneCondizionalita: 86,
    Esportatore_Codifiche_Cultivar: 87,
    Esportatore_Codifiche_SpecieVegetali: 88,
    Produzioni_XLS: 89,
    FiltroStrube: 90,
    Esportazione_AnagraficaProdotti: 91,
    PacchettoIgiene_RegistroFornitori: 92,
    PacchettoIgiene_RegistroClienti: 93,
    PacchettoIgiene_SchedaUsoAlimentiOGM: 94,
    PacchettoIgiene_RegistroAlimentazioneStalla: 95,
    PacchettoIgiene_RegistroRazionamento: 96,
    PacchettoIgiene_RegistroAnalisiNonConformi: 97,
    Esportazione_AnagraficaContatti: 99,
    Esportazione_CellulariContatti: 100,
    Analisi_Vino_Derivanti_Da_Travasi: 101,
    Bilanci_DiVerifica_Confronto: 102,
    Nota_Accredito: 103,
    Mastrino: 104,
    Esportazione_OP_Gest_Coop: 105,
    Registri_Preparazioni: 106,
    EtichetteVascheEnologiche: 107,
    Bilancio_Fertilizzazioni: 109,
    Programmazione_Vegetale: 110,
    Esporta_GiasToXMLPubblico: 111,
    Esporta_Conferimenti_JDEdwards: 112,
    Buono_Accettazione_Diversi: 113,
    Buono_Accettazione: 114,
    Registro_Fertilizzazioni: 115,
    SchedaTracciabilita_Animale: 116,
    RaccoltaDatiAnagrafici: 117,
    Importa_RaccolteConferimenti_DaRintraccio: 118,
    ADD_Filtro_Report_Accettazione_DaDiversi: 119,
    ADD_Riepilogo_Conf_XSpecie: 120,
    ADD_EC_Bolle_Accettazione_DaDiversi: 121,
    ADD_EC_Imballi: 122,
    ADD_Saldo_Imballi: 123,
    ADD_Export_Bolle_Accettazione_DaDiversi: 124,
    ADD_Export_Traportatori: 125,
    Importazione_DDT_PianoColturale: 126,
    Mandato_Trasmissione_Telematica_Dati: 127,
    DOCO: 128,
    DAA: 129,
    Impegnativa_Orticole_Gest_Annuale: 130,
    Impegnativa_Orticole_Gest_Breve: 131,
    Impegnativa_Orticole_Industria: 132,
    Impegnativa_Pomodoro_Industria: 133,
    Impegnativa_Fagiolino_Mercato_Fresco: 134,
    ImportaContatti_XLS2GIAS: 135,
    Certificato_Pomodoro: 136,
    Certificato_Pomodoro_Interno: 137,
    Certificato_Pomodoro_Esterno: 138,
    Registro_CaricoScarico_Pomodoro: 139,
    Esporta_ConferimentiPomodoro_Agrea: 140,
    Esporta_BolleAccettazione2AltroClienteGias: 141,
    ExportExcel_MonitoraggioCE: 142,
    ADD_ExportExcel_CertificatiPomodoro: 143,
    SchedaCampagna_Ricette: 144,
    GestioneRicette_Edit: 145,
    ExportExcel_MonitoraggioCE_Aggregata: 146,
    GestioneEtichette_Trasformati: 147,
    LibroConferimenti_XLS: 148,
    RegistroTrattamenti_Veneto: 149,
    SchedaCampagna_Multicentro: 150,
    RiepilogoImpiegoSuperfici_Multiazienda: 151,
    Eurep_Gap_Multicentro: 152,
    SchedaPreparati_Biologico: 153,
    Notifica_Biologico: 154,
    RiBa_Report_Presentazione: 155,
    RiBa_Export_CBI: 156,
    Listini_XLS: 157,
    DDT_Contabilizzato_Emesso: 158,
    Ordine: 159,
    AgentiProvvigioni_XLS: 160,
    Eurep_Gap_Multicentro_Immediata: 161,
    Report_Incongruenze_CatastoVSAgrea: 162,
    Preventivo_Vendita: 163,
    Scheda_Rilievi: 164,
    PianoColturaleCatasto: 166,
    GiornaleContabile: 167,
    Ordine_Acquisto: 168,
    FF_Etichette: 169,
    Liquidazione_Soci: 170,
    Allegato_CatastoeValorizzazioni: 171,
    Esportazione_OP_Produttori: 172,
    Esportazione_OP_Catasto: 173,
    ADD_ExcelTracciabilitaConferimenti: 174,
    FreshFood_BollaAccettazione: 175,
    FreshFood_DistintaCarico_Accettazione: 176,
    FreshFood_AutoDDT_Accettazione: 177,
    SchedaMagazzinoMovimentiExcel: 178,
    ConferimentoUva_DDTRicevuto: 165,
    ConferimentoUva_DistintaCarico: 179,
    ConferimentoUva_AutoDDT: 180,
    Registro_Fertilizzazioni_Massivo: 181,
    Registro_Trattamenti_Massivo: 182,
    Conf_FiltroStampe: 183,
    Conf_EC_Imballi: 184,
    Conf_Saldo_Imballi: 185,
    Conf_Riepilogo_Conferimenti: 186,
    Conf_Tracciabilita: 187,
    Bilancio_SezioniContrapposte: 188,
    EstrattoConto_Contatti: 189,
    Cespiti_FiltroStampe: 190,
    SchedaCampagna_ProvAut_Trento: 191,
    SchedaCampagna_Multi_Lombardia: 192,
    FreshFood_BollaCampionatura: 193,
    RisultatoAnalisiConformita: 194,
    FreshFood_FatturaLiquidazioneSoci: 195,
    FreshFood_PagatiSuConferito: 196,
    FreshFood_AutofatturaLiquidazioneSoci: 197,
    FreshFood_RiepilogoLiquidazioneSoci: 198,
    FreshFood_PagatiSuCampionato: 199,
    Analisi_Progetti: 200,
    SchedaInterventiAgronomici: 201,
    EsportazioneAgeaTxtCSV: 202,
    RegistroAziendaleUnico: 203,
    SchedaCatastoeUtilizzi: 204,
    RegistroTrattamentiVeneto_StdCondizionalita: 205,
    RiepiloghiAccise: 206,
    DAA_GaranzieCircolanti: 207,
    DAA_PariteSospensione: 208,
    MVV: 209,
    Report_Vendita_PDF: 210,
    ReportRisultatoFiltroneG2G: 211,
    EsportazionePomodoroIndustriaOINordItalia: 212,
    RiepilogoProdottiUtilizzati: 213,
    PassaportoMaterialeVivaistico: 214,
    ReportRisultatoFiltroneIncludiVisita: 215,
    Bilancio_Fertilizzazioni_Dettagliato: 216,
    Conf_Esportazione_BolleFF_XLS: 217,
    Filtro_StampeBiologico: 218,
    Conf_EsportazionexTrasportatori_XLS: 219,
    Conf_RiepilogoxArticolo: 220,
    Conf_EC_Bolle: 221,
    Conf_Certificato_Pomodoro: 222,
    Conf_Esportazione_CertificatiPomodoro_XLS: 223,
    UMA_RichiestaCarbPrevisioneLav: 224,
    UMA_VerbaleIstruttoriaRichCarb: 225,
    UMA_RendicontazioneCarb: 226,
    UMA_IstruttoriaRendCarb: 227,
    EstrazioneCatastoAffitti: 228
};

var elencoSezioniVuote = '';
var ElencoCulture = null;