import { AfterViewInit, Component, Inject, OnInit, ViewChild } from '@angular/core';
import { SelectionEvent } from '@progress/kendo-angular-grid/selection/types';
import { TooltipDirective } from '@progress/kendo-angular-tooltip';
import { GISGeometrySelectionService } from 'app/GIS/services/gis-geometry-selection.service';
import { GridImpiantiService } from 'app/quaderno-di-campagna/agenda-edit/service/grid-impianti/grid-impianti.service';
import { GiasKendoGridComponent } from 'gias-kendo-grid';
import { GRID_HTTP_TOKEN, SelectedOpts } from 'gias-kendo-grid';
import { GridPublicService } from 'gias-kendo-grid';
import { generateGridProviders } from 'gias-kendo-grid';
import { combineLatest, forkJoin, Subject, take } from 'rxjs';
import { CalcoloSuperficiService } from '../../service/calcolo-superfici.service';
import { GridImpiantiHttpService, GridImpiantiServerResult } from '../../service/grid-impianti/grid-impianti-http.service';
import { QdCService } from '../../service/qdc.service';
import {cloneDeep} from "lodash";


// AUTOGENERATED CODE TO MAP THE GRID MODEL
interface GruppoFinalita {
    specieCod: number;
    codice: number;
    descrizione: string;
}

interface ObjDisciplinare {
    disciplinarePubblicoPrivato: number;
    regolamentoConcimazione?: any;
    raggruppamentiColturaliDPI?: any;
    gruppoFinalita: GruppoFinalita;
    flagProtetto: number;
    idTr: number;
    codice: string;
    descrizione: string;
}

interface GridRowElement {
    PIVA: string;
    SA_COD: number;
    APPEZZA: number;
    ID_REG: number;
    Validita_Inizio: string;
    Validita_Fine: string;
    Sup_Imp: number;
    Cop_Cod: number;
    Copertura: string;
    Imp_Cod: number;
    Foral_Cod: number;
    Port_Cod: number;
    Veg_Cod: number;
    CUL_COD: number;
    Cul_Des: string;
    GRVA_Cod_VEG: number;
    Campo_Cod: number;
    SUP_APP: number;
    APP_NOME: string;
    DistBZ_CorpiIdrici: number;
    DistBZ_AreeResPub: number;
    DistBZ_Allevamenti: number;
    DistBZ_VegNatNonColt: number;
    SupBZ_Riduzione: number;
    Validita_inizio_Appezzamento: string;
    Validita_fine_Appezzamento: string;
    GRFI_COD: number;
    Grfi_Des: string;
    P_Impianto: number;
    TRA_FILA: number;
    SU_FILA: number;
    Progetto_Cod: string;
    Progetto: string;
    Stato_Impianto: number;
    Regolamento: number;
    Reg_Des: string;
    Disciplinare_Des: string;
    Finanziamento: number;
    Disciplinare_PubblicoPrivato: number;
    Disciplinare?: any;
    Disciplinare_Cod: number;
    id_rcdpi: number;
    info: string;
    Validita_Inizio_Distinta: string;
    Validita_Fine_Distinta: string;
    Codici_Anagrafe_Des: string;
    Codice_Anagrafe: number;
    CodBioApp: string;
    Capitolato_Privato_Des: string;
    Capitolato_Privato_Codice: number;
    Data_Semina_Prevista: string;
    Data_Raccolta_Prevista: string;
    Data_Fioritura_Prevista: string;
    FF_COD?: any;
    Campo_Des: string;
    Data_Semina: string;
    Data_Raccolta: string;
    Data_Fioritura: string;
    Fase_Cod_Corrente: number;
    Data_Fase_Corrente: string;
    N_Massimo: string;
    N_Distribuito: string;
    N_Residuo: string;
    P_Massimo: string;
    P_Distribuito: string;
    P_Residuo: string;
    K_Massimo: string;
    K_Distribuito: string;
    K_Residuo: string;
    Mg_Massimo: string;
    Mg_Distribuito: string;
    Mg_Residuo: string;
    CU_Massimo: string;
    CU_Distribuito: string;
    CU_Residuo: string;
    SpecieAgea: string;
    CultivarAgea: string;
    rag_soc: string;
    sa_nome: string;
    Veg_Des: string;
    Imp_Des: string;
    Grva_Des: string;
    RifNumerico: string;
    Foral_Des: string;
    Port_Des: string;
    StaticMapBase64String: string;
    App_Nome_Anagrafica: string;
    catasto: string;
    kendoKey: string;
    Sup_Imp_help: number;
    Descrizione_Unica: string;
    GisWkt?: any;
    GisWktGps?: any;
    GisWktSistemaRiferimento?: any;
    GisTipoEntita_cod?: any;
    GisLayerCod?: any;
    Fase_Corrente: string;
    Sup_Riduzione_BufferZone: number;
    Perc_Riduzione_Deriva: number;
    Id_ClasseTessitura: string;
    Str_ClasseTessitura: string;
    ListaClassiTessitura: any[];
    N_Max: string;
    P_Max: string;
    K_Max: string;
    Mg_Max: string;
    Obj_Disciplinare: ObjDisciplinare;
    Flag_Protetto: number;
    CarenzaStr: string;
}

@Component({
    standalone: false,
    selector: 'app-grid-impianti',
    templateUrl: './grid-impianti.component.html',
    styleUrls: ['./grid-impianti.component.css'],
    providers: [
        // eslint-disable-next-line no-use-before-define
        ...generateGridProviders(GridImpiantiHttpService, GridImpiantiComponent), CalcoloSuperficiService
    ]
})
export class GridImpiantiComponent implements OnInit, AfterViewInit {

    @ViewChild(TooltipDirective) public tooltipDir: TooltipDirective;
    @ViewChild('GridImpianti') GridImpiantiElRef: GiasKendoGridComponent;

    private data: GridImpiantiServerResult | null = null;
    private dataLoaded$ = new Subject<boolean>();
    private viewLoaded$ = new Subject<boolean>();
    private rowsLoaded$ = new Subject<boolean>();

    constructor(
        private gridimpiantiservice: GridImpiantiService,
        private qdcservice: QdCService,
        private gridpublicService: GridPublicService,
        private gisGeometrySelectionService: GISGeometrySelectionService,
        @Inject(GRID_HTTP_TOKEN) private gridhttpService: GridImpiantiHttpService
    ) {
        this.gridhttpService.impiantiLoaded$.subscribe(data => {
            this.data = data;
            this.dataLoaded$.next(true);
        });

        this.gisGeometrySelectionService.geometrySelectedFromMap$
            .subscribe((keys) => this.handleSelectedGeometries(keys));

        this.qdcservice.eventiPostSelectionChangeGridImpianti
            .subscribe(rows => {
                if (rows) {
                    this.gridimpiantiservice.EventiPostselectionChangeGridImpianti(rows);
                }
            });

        this.rowsLoaded$
            .asObservable()
            .pipe(take(1))
            .subscribe(() => this.handleSelectedGeometries(this.gisGeometrySelectionService.getCurrentSelection()));
    }

    ngOnInit(): void {
        this.qdcservice.GridImpiantiHttpService = this.gridhttpService;
        this.qdcservice.GridImpiantiPublicService = this.gridpublicService;
    }

    ngAfterViewInit(): void {
        this.gridimpiantiservice.settooltip(this.tooltipDir);
        this.viewLoaded$.next(true);
    }

    onSelected(event: SelectionEvent): void {
        const selected = event.selectedRows.map((item) => this.getKeyFromSelectedItem(item.dataItem));
        this.gisGeometrySelectionService.addFromOutside(...selected as string[]);

        const deselected = event.deselectedRows.map((item) => this.getKeyFromSelectedItem(item.dataItem));
        this.gisGeometrySelectionService.removeFromOutside(...deselected as string[]);
    }

    rowsLoaded() {
        this.rowsLoaded$.next(true);

        if(this.qdcservice.Apertura_QdC && this.qdcservice.Apertura_QdC.flag_QdC_Aperta_da_Altra_Pagina && this.qdcservice.Apertura_QdC.flag_Selezione_Impianti){

            if(this.qdcservice.GridImpiantiPublicService && this.qdcservice.GridImpiantiPublicService?.getValue()?.data?.rows?.length > 0){

                let righe_selezionate_grid = this.gridimpiantiservice.kGetElementiSelezionati(cloneDeep(this.qdcservice.GridImpiantiPublicService.getValue().data.rows));

                if(righe_selezionate_grid && righe_selezionate_grid.length > 0){

                  this.qdcservice.Apertura_QdC.flag_Selezione_Impianti = false;

                  this.qdcservice.AggiornaRigheSelezionateGriglia(righe_selezionate_grid,[]);

                  this.gridimpiantiservice.EventiPostselectionChangeGridImpianti(this.qdcservice.GridImpiantiPublicService.getValue().data.rows,true);
                }

            }


        }
    }

    private handleSelectedGeometries(keys: [string, boolean][]): void {
        if (this.data == null || this.GridImpiantiElRef.rows == null) {
            return;
        }

        // if service is not initialized, get present selection from grid
        if (!this.gisGeometrySelectionService.isInitialized()) {
            const preSelected = this.GridImpiantiElRef.rows
                .filter((row) => row['Selected'] === true)
                .map((row) => this.getKeyFromSelectedItem(row as GridRowElement));

            if (preSelected.length > 0) {
                this.gisGeometrySelectionService.addFromOutside(...preSelected as string[]);
            }

            return;
        }

        const nonSelected: { key: string; value: GridRowElement }[] = [];

        for (const row of this.GridImpiantiElRef.rows) {
            const rowKey = this.getKeyFromSelectedItem(row as GridRowElement);

            const key = keys.find((item) => item[0].includes(rowKey));
            if (key == null) {
                nonSelected.push({ key: rowKey, value: row as GridRowElement });
                continue;
            }

            const isSelected = key[1];
            row['Selected'] = isSelected;

        }

        // this.logNonSelected(nonSelected);
        let selectedRows = this.GridImpiantiElRef.rows.filter(row =>(row['Selected'] === true));
        let deselectedRows = this.GridImpiantiElRef.rows.filter(row =>(row['Selected'] === false));
        this.qdcservice.AggiornaRigheSelezionateGriglia(selectedRows, deselectedRows);
        this.GridImpiantiElRef.refresh();
    }

    private getKeyFromSelectedItem(item: GridRowElement): string {
        return `§${item.PIVA}§${item.SA_COD}§${item.Campo_Cod}§${item.APPEZZA}§${item.ID_REG}`;
    }

    private logNonSelected(nonSelected: { key: string; value: GridRowElement }[]): void {
        console.log('The following rows have not been selected:');
        console.table(nonSelected.map(item => ({ 'name': item.value.APP_NOME, 'key': item.key })));

        console.log('Table of current selection:');
        console.table(this.gisGeometrySelectionService.getCurrentSelection());
    }
}
